### ISSUE TITLE
Add “perf” type to Conventional Commit Builder

### ISSUE THREAD

**Issue by AquariusLeo** [fletch-r/simple-commit#44]
I want use “perf” type to Conventional Commit Builder, or can you open the right to custom the type of commit message? Thanks a lot.
![image](https://github.com/fletch-r/simple-commit/assets/38411898/f58e72b6-4391-48c0-91fa-476900110526)

**Comment by fletch-r** [comment]
Hi @AquariusLeo ,

Thank you for the suggestion I like the idea of the user being able to customise their types.

I'll get working on that now.

:)
